"""
Django settings for mozi project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9at-x$!x8(@ui_3ds7oq-2t0*4s9xi!haf(9o7+^toe@&(nvfl'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blog',
    'chat',
    'Attendance',  
    'recognizer',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mozi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # FIX: اضافه کردن مسیر پوشه templates اصلی
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mozi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i1n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = "blog.MyUser"
LOGIN_URL = '/login/' 

# مسیری که بعد از ورود موفق کاربر به آن هدایت می‌شود
LOGIN_REDIRECT_URL = '/dashboard/'


import os

# URL عمومی که فایل‌ها از طریق آن در مرورگر در دسترس خواهند بود
MEDIA_URL = '/media/'

# مسیر کامل در سرور که فایل‌های آپلود شده در آن ذخیره می‌شوند
# ما یک پوشه به نام 'mediafiles' در کنار manage.py می‌سازیم
MEDIA_ROOT = os.path.join(BASE_DIR, 'mediafiles')
# (جدید) مسیر پوشه static اصلی
STATIC_ROOT = BASE_DIR / 'staticfiles'

# mozi/settings.py
# ... (بالای فایل) ...

JAZZMIN_SETTINGS = {
    "site_title": "Mozi Admin",
    "site_header": "Mozi School",
    "site_brand": "Mozi",
    "welcome_sign": "به پنل مدیریت مدرسه Mozi خوش آمدید ✨",
    "copyright": "Mozi © 2025",
    "search_model": "blog.MyUser",

    "topmenu_links": [
        {"name": "داشبورد", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"model": "blog.MyUser"},
        {"model": "Attendance.Attendance"},
    ],

    "show_sidebar": True,
    "navigation_expanded": True,

    # لوگو اگر داشتی جایگزین کن
    "site_logo": None,
    "login_logo": None,
    "login_logo_dark": None,

    "language_chooser": False,
}

JAZZMIN_UI_TWEAKS = {
    "theme": "darkly",
    "dark_mode_theme": "cyborg",
    "navbar_fixed": True,
    "footer_fixed": False,
    "actions_sticky_top": True,
    "button_classes": {
        "primary": "btn btn-outline-info",
        "secondary": "btn btn-outline-light",
        "danger": "btn btn-outline-danger",
    },
}
JAZZMIN_SETTINGS["custom_css"] = "jazzmin/custom.css"
