# Generated by Django 5.2.7 on 2025-11-06 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('confidence', models.FloatField(blank=True, null=True, verbose_name='اعتماد تشخیص')),
                ('method', models.CharField(default='face-api.js', max_length=50, verbose_name='روش ثبت')),
                ('device', models.CharField(blank=True, max_length=100, null=True, verbose_name='دستگاه ثبت')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'حضور',
                'verbose_name_plural': 'حضورها',
                'ordering': ('-timestamp',),
            },
        ),
    ]
